name: "FLZT 每日签到 + 转换流量"

on:
  schedule:
    - cron: "38 1,17 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          EMAIL: ${{secrets.EMAIL}}
          PASSWORD: ${{secrets.PASSWORD}}
          TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
          TG_USER_ID: ${{secrets.TG_USER_ID}}
        run: |
          python main.py
      - name: Keep alive
        run: |
          mkdir .keep-alive
          date > .keep-alive/keep-alive.md
      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: keep-alive
          build_dir: .keep-alive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
